services:
  ass-saver:
    build:
      context: .
      args:
        VERSION: "1.0.1"
    image: unraiders/ass-saver
    container_name: ass-saver
    environment:
      - VERSION=1.0.1
    ports:
      - "8000:8000"
    restart: unless-stopped
